/* Generated by Yosys 0.38 (git sha1 543faed9c8c, clang++ 17.0.6 -fPIC -Os) */

module full_adder(A_XX, B_YY, C_in, Sum_XXYY, C_out);
  wire _0_;
  wire _1_;
  wire _2_;
  input A_XX;
  wire A_XX;
  input B_YY;
  wire B_YY;
  input C_in;
  wire C_in;
  output C_out;
  wire C_out;
  output Sum_XXYY;
  wire Sum_XXYY;
  sky130_fd_sc_hd__inv_2 _3_ (
    .A(B_YY),
    .Y(_0_)
  );
  sky130_fd_sc_hd__xnor2_2 _4_ (
    .A(A_XX),
    .B(C_in),
    .Y(_1_)
  );
  sky130_fd_sc_hd__nand2_2 _5_ (
    .A(A_XX),
    .B(C_in),
    .Y(_2_)
  );
  sky130_fd_sc_hd__o21ai_2 _6_ (
    .A1(_0_),
    .A2(_1_),
    .B1(_2_),
    .Y(C_out)
  );
  sky130_fd_sc_hd__xnor2_2 _7_ (
    .A(B_YY),
    .B(_1_),
    .Y(Sum_XXYY)
  );
endmodule
